# Generated by Django 3.2.9 on 2021-12-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasia', '0002_alter_shopitem_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
