# Generated by Django 3.2.9 on 2022-01-01 19:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('plantasia', '0003_alter_shopitem_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image_src',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='shopitems/images/default_image.png', force_format='JPEG', keep_meta=False, null=True, quality=75, size=[1250, 1250], upload_to='shopitems/images/'),
        ),
    ]
