# Generated by Django 3.2.9 on 2022-01-03 23:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('plantasia', '0006_alter_shopitem_image_src'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='image_src',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='shopitems/images/default_image.png', force_format='JPEG', keep_meta=False, null=True, quality=75, size=[1250, 1250], upload_to='shopitems/uploads/'),
        ),
    ]
